aweProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myblog/', include('myblog.urls', namespace='myblog')),
]

myblog/urls.py
from django.urls import path
from . import views

app_name = '[myblog]'
urlpatterns = [
    path('home/', views.home),
    path('home/android/', views.mAndroid, name='android'),
    path('home/testfrom/', views.testForm),

]

myblog/models.py
from django.db import models


# Create your models here.
class user(models.Model):
    name = models.TextField(max_length=20)
    psw = models.CharField(max_length=16)

    # 后台表显示的标题
    def __str__(self):
        return self.name

myblog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from myblog import models


# Create your views here.

def home(request):
    return render(request, 'home.html')


def mAndroid(request):
    return render(request, 'android.html')


def testForm(request):
    name = request.POST['mname']
    psw = request.POST['psw']
    isExit = models.user.objects.get_or_create(name=name, psw=psw)
    if isExit:
        return '已经存在信息'
    else:
        return '插入成功'

myblog/templates/android.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>android</title>
</head>
<body>


</body>
</html>

myblog/templates/home.html
<!DOCTYPE html>
{% load static %}
{% load admin_urls %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/mine.css' %}">

    <title>我的博客</title>
    <script>
        //jquery选择器
        $(document).ready(function () {
            $("#saa").click(function () {
                alert("aaaaaaaa")
            })
        })
    </script>
</head>
<body>
{#导航栏#}
<div class="top-nav-back">
    <div class="container">
        <h1 id="welcome">welcome my blog</h1>
        <div class="fr">
            <ul>
                <li><a href="#" target="_self">个人简历</a></li>
                <li><a href="#" target="_self">我们的爱</a></li>
                <li><a href="{% url 'myblog:android' %}" target="_self">android</a></li>
                <li><a href="#" target="_self">python</a></li>
            </ul>
        </div>

    </div>

</div>
<div>
    <form action="testfrom/" method="post">
        姓名: <input type="text" name="mname" required> <br>
        密码: <input type="password" name="psw" required> <br>
        {% csrf_token %}
        <input type="submit" value="提交">
    </form>
</div>
<img id='mg' src="{% static 'img/abc.jpg' %}" width="100px" height="100px">
<div class="ghost-center">
    <P>你毕业才两年怎么会有三年的经验，你毕业才两年怎么会有三年的经验？</P>

</div>


<script src="{% static 'bootstrap/js/jquery-3.3.1.min.js' %}" rel="script"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}" rel="script"></script>
<script src="{% static 'javascript/main.js' %}" type="text/javascript"></script>
</body>
</html>